# Generated by Django 5.2 on 2025-07-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('data', 'Data Science'), ('ai', 'AI & ML')], default='web', max_length=50),
        ),
    ]
