# Generated by Django 5.2 on 2025-07-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web', 'Web'), ('frontend', 'Frontend'), ('ai', 'AI & ML'), ('mobile', 'Mobile')], default='web', max_length=50),
        ),
    ]
