# Generated by Django 5.2 on 2025-07-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Course', 'Course'), ('Internship', 'Internship'), ('Competition', 'Competition')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificates/images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='certificates/pdfs/')),
            ],
        ),
    ]
