# Generated by Django 5.2 on 2025-07-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='certificates/')),
                ('pdf', models.FileField(upload_to='certificates/')),
                ('linkedin_url', models.URLField()),
            ],
        ),
    ]
