# Generated by Django 5.2 on 2025-07-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='image',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='linkedin_url',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
